In [28]:
import numpy as np
import pandas as pd
import pickle

filename = "heart.csv"
filename1= "in_file_1.csv"
filename2 = "results.xlsx"


In [3]:
df = pd.read_csv(filename)
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [5]:
data = np.loadtxt(filename, delimiter=",", skiprows=1)
print(data)

[[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [6]:
data = np.genfromtxt(filename,delimiter=",",dtype=None,names=True,encoding="utf-8-sig")
print(data)
print(data.dtype)

[(63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1, 1)
 (37, 1, 2, 130, 250, 0, 1, 187, 0, 3.5, 0, 0, 2, 1)
 (41, 0, 1, 130, 204, 0, 0, 172, 0, 1.4, 2, 0, 2, 1)
 (56, 1, 1, 120, 236, 0, 1, 178, 0, 0.8, 2, 0, 2, 1)
 (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1)
 (57, 1, 0, 140, 192, 0, 1, 148, 0, 0.4, 1, 0, 1, 1)
 (56, 0, 1, 140, 294, 0, 0, 153, 0, 1.3, 1, 0, 2, 1)
 (44, 1, 1, 120, 263, 0, 1, 173, 0, 0. , 2, 0, 3, 1)
 (52, 1, 2, 172, 199, 1, 1, 162, 0, 0.5, 2, 0, 3, 1)
 (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1)
 (54, 1, 0, 140, 239, 0, 1, 160, 0, 1.2, 2, 0, 2, 1)
 (48, 0, 2, 130, 275, 0, 1, 139, 0, 0.2, 2, 0, 2, 1)
 (49, 1, 1, 130, 266, 0, 1, 171, 0, 0.6, 2, 0, 2, 1)
 (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1)
 (58, 0, 3, 150, 283, 1, 0, 162, 0, 1. , 2, 0, 2, 1)
 (50, 0, 2, 120, 219, 0, 1, 158, 0, 1.6, 1, 0, 2, 1)
 (58, 0, 2, 120, 340, 0, 1, 172, 0, 0. , 2, 0, 2, 1)
 (66, 0, 3, 150, 226, 0, 1, 114, 0, 2.6, 0, 0, 2, 1)
 (43, 1, 0, 150, 247, 0, 1, 171, 0, 1.5, 2, 0,

In [12]:
def load_file(filename):
    with open(filename,encoding="utf-8-sig") as f:
        data,cols = [],[]
        for i, line in enumerate(f.read().splitlines()):
            if i == 0:
                cols += line.split(",")
            else:
                data.append([float(x) for x in line.split(",")])
        df = pd.DataFrame(data,columns=cols)
    return df

load_file(filename).head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  3.0     145.0  233.0  1.0      0.0    150.0    0.0      2.3   
1  37.0  1.0  2.0     130.0  250.0  0.0      1.0    187.0    0.0      3.5   
2  41.0  0.0  1.0     130.0  204.0  0.0      0.0    172.0    0.0      1.4   
3  56.0  1.0  1.0     120.0  236.0  0.0      1.0    178.0    0.0      0.8   
4  57.0  0.0  0.0     120.0  354.0  0.0      1.0    163.0    1.0      0.6   

   slope   ca  thal  target  
0    0.0  0.0   1.0     1.0  
1    0.0  0.0   2.0     1.0  
2    2.0  0.0   2.0     1.0  
3    2.0  0.0   2.0     1.0  
4    2.0  0.0   2.0     1.0

In [3]:
pf =pd.read_csv(filename1) 
pf.shape

frame_no detected_pose
0        33     jump_peak
1        68     jump_peak
2        80       landing
3       129    transition
4        91    transition
5        89       landing
6        66     jump_peak
7        48     jump_peak
8        29    transition
9        42     jump_peak

In [31]:
df= pd.read_excel(filename2,index_col=0)
df.shape

(13001, 7)

In [15]:
data = np.random.random(size=(5, 3))
print(data)
df = pd.DataFrame(data=data,columns=["A","B","C"])
df

[[0.4550666  0.86298785 0.79990435]
 [0.67939806 0.67172233 0.40379045]
 [0.98956784 0.75652285 0.96229716]
 [0.49730678 0.69345959 0.69083444]
 [0.32638612 0.01941202 0.86575633]]


A         B         C
0  0.455067  0.862988  0.799904
1  0.679398  0.671722  0.403790
2  0.989568  0.756523  0.962297
3  0.497307  0.693460  0.690834
4  0.326386  0.019412  0.865756

In [16]:
df = pd.DataFrame(data={"A":[1,2,3],"B":["Sam","Alex","John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [29]:
df = pd.DataFrame(np.random.random(size=(10000,4)),columns=["A","B","C","D"])
df

A         B         C         D
0     0.512461  0.960765  0.387521  0.373920
1     0.123385  0.960388  0.412424  0.613502
2     0.728008  0.772359  0.584524  0.537017
3     0.406705  0.086974  0.370203  0.573786
4     0.383202  0.878969  0.743885  0.920655
...        ...       ...       ...       ...
9995  0.721554  0.949960  0.217280  0.005346
9996  0.155442  0.332859  0.623381  0.530517
9997  0.256007  0.055230  0.486617  0.821591
9998  0.101146  0.385255  0.552149  0.922116
9999  0.057530  0.418132  0.907219  0.081892

[10000 rows x 4 columns]

In [18]:
df.to_csv("save.csv",index=True,float_format="%0.4f")


In [20]:
pip install tables

Note: you may need to restart the kernel to use updated packages.


In [22]:
df.to_hdf("save.hdf", key="data",format="table")